on: push
name: Lint Dockerfiles
jobs:
  lintAllTheFiles:
    name: Lint all the files
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Lint all the files
      uses: docker://cdssnc/docker-lint
